import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./_components/providers/store.provider";
import { plex_mono } from "./_utils/fonts";

export const metadata: Metadata = {
  title: "Mini Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plex_mono.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
