import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./_components/providers/store.provider";
import { plex_mono } from "./_utils/fonts";
import { ThemeModeScript } from "flowbite-react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Mini Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={plex_mono.className}>
        <StoreProvider>
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
